"""empty message

Revision ID: 42b4bd7a0f3f
Revises: 115b3ec15167
Create Date: 2017-01-12 16:07:53.306847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b4bd7a0f3f'
down_revision = '115b3ec15167'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_remind', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_remind')
    # ### end Alembic commands ###
