"""empty message

Revision ID: 49a5d0040b0e
Revises: 7c02e4252027
Create Date: 2017-01-12 18:44:40.649207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a5d0040b0e'
down_revision = '7c02e4252027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anchors', sa.Column('users_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anchors', 'users_count')
    # ### end Alembic commands ###
