"""empty message

Revision ID: e163567be09f
Revises: dc9ba8e7a29a
Create Date: 2017-01-12 19:10:26.867656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e163567be09f'
down_revision = 'dc9ba8e7a29a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anchors', sa.Column('users_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anchors', 'users_count')
    # ### end Alembic commands ###
